server:
  port: 80
  servlet:
    context-path: / #项目的上下文路径
spring:
  datasource:
    url: jdbc:mysql:///facepay?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&autoReconnect=true&useSSL=false
    username: r**
    password: r**
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      idle-timeout: 60000
      maximum-pool-size: 30
      minimum-idle: 10
  thymeleaf:
    cache: false
# mybatis plus配置
mybatis-plus:
  mapper-locations: classpath:/mybatis/*.xml #加载映射文件
  type-aliases-package: com.itxiong.facepay.domain #别名搜索的包
  configuration:
    lazy-loading-enabled: false #打开懒加载
    aggressive-lazy-loading: false #关闭积极懒加载
  global-config:
    banner: false
face:
  config:
    api-key: 7_XZdAaI85OcGPvnXID***8XOENQMO94
    api-secret: xiLl7jM1jxU6Etiha4g***nFXwBRk6
    outer-id: face_pay

